behaviors:
  Landing:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      vis_encode_type: simple
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    behavioral_cloning:
      demo_path: MAVControlWithSNN/Demonstrations/LandingYaxis.demo
      strength: 0.5
      steps: 500000
      batch_size: 64
      num_epoch: 3
      samples_per_update: 512
    max_steps: 100000000
    time_horizon: 64
    summary_freq: 10000

environment_parameters:
  droneMaxStartY:
    curriculum:
      - name: ExtraLowAltitude
        completion_criteria:
          measure: reward
          behavior: Landing
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.9
        value: 1.5
      - name: LowAltitude
        completion_criteria:
          measure: reward
          behavior: Landing
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.9
        value: 10.0
      - name: MediumAltitude
        completion_criteria:
          measure: reward
          behavior: Landing
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.9
        value: 25.0
      - name: MediumHighAltitude
        completion_criteria:
          measure: reward
          behavior: Landing
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.9
        value: 50.0
      - name: HighAltitude
        value: 100.0